### ISSUE TITLE
Add a license for the repository

### ISSUE THREAD

**Issue by xuanruiqi** [mid-kid/r8822be#4]
Since the bulk of code comes from the Linux kernel, I suppose GPL will work

**Comment by mid-kid** [comment]
If this is to include it in the (user) repository of any distribution, please don't. This was mostly meant as a copy for personal use and sometimes even kernel panics on recent kernels, as I hardly know how most of this code works or how to fix it, beyond copying stuff from the upstream git every once in a bit. I don't plan to support this very long.
Instead, consider reporting the issues you're experiencing with the equivalent upstream driver to the kernel mailing list. Most of the issues I had with it have been resolved by now, with only 5GHz AP support being lacking.

The file's headers say GPL-2.0 so I'll add that.
