### ISSUE TITLE
Wifi problem turning again

### ISSUE THREAD

**Issue by prabhavagrawal7** [mid-kid/r8822be#7]
Either after some weeks or after restarting, ubuntu is unable to detect my wifi card.

**Comment by prabhavagrawal7** [comment]
**while using command:-**
sudo modprobe r8822be
**I got this error :-**
ERROR: could not insert 'r8822be': Operation not permitted

**Comment by mid-kid** [comment]
"Operation not permitted" sounds more like a permission issue, or other misconfiguration. I don't know enough about Ubuntu to help.
Why aren't you using the default driver for this chipset?

**Comment by prabhavagrawal7** [comment]
Hi mid-kid,
Actually my driver issue got solved after I turned off secure boot.
Otherwise I have to resync the date & time of windows every time this
problem shows up.
Almost every driver issue got solved after that.
Thanks for help
Your's Sincerely
Prabhav Agrawal

**Comment by mid-kid** [comment]
Secure boot being an issue makes sense, I'll keep that in mind. Thanks for explaining.
